### ISSUE TITLE
Please submit your UW NetID.

### ISSUE THREAD

**Issue by acannistra** [uwseds-sp20/homework-1-manipulating-data-zlavogb#2]
Hi @zlavogb  ––

Thanks for starting the homework assignment! Looking forward to your submission.

As discussed in class, you're required to add your name, UW NetID, and GitHub Account ID to the following spreadsheet: https://docs.google.com/spreadsheets/d/1JSV5zcRc8tYqyVWzk_E5mOyfJdblOMy5PeaNEtdDvjE/edit#gid=0. You will need to be logged-in to your UW Google account for access.

Do this ASAP in order to receive credit for your submission.

Thanks!
Tony Cannistra (UWSEDS TA)

**Comment by zlavogb** [comment]
Thanks for the reminder, Tony. I have added my information to the spreadsheet.

**Comment by acannistra** [comment]
Thanks!
